# Generated by Django 3.2.9 on 2021-12-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Empregadores',
            },
        ),
        migrations.CreateModel(
            name='VagaDeEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empregos', to='core.empregador')),
            ],
            options={
                'verbose_name_plural': 'Vagas de Emprego',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.vagadeemprego')),
            ],
            options={
                'verbose_name_plural': 'Inscricoes',
            },
        ),
    ]
