# Generated by Django 3.2.9 on 2021-11-29 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empregador',
            options={'verbose_name_plural': 'Empregadores'},
        ),
        migrations.CreateModel(
            name='VagaDeEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empregos', to='core.empregador')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.empregador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inscricoes',
            },
        ),
    ]
