# Generated by Django 3.2.9 on 2021-11-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211129_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vagadeemprego',
            options={'verbose_name_plural': 'Vagas de Emprego'},
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='empregador',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='vagaDeEmprego',
            field=models.ForeignKey(default='Chose One', on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.vagadeemprego'),
        ),
    ]
