# Generated by Django 3.2.9 on 2021-11-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211129_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='vagaDeEmprego',
        ),
    ]
