# Generated by Django 3.2.8 on 2021-11-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_inscricao_vagadeemprego'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='vagaDeEmprego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.vagadeemprego'),
        ),
    ]
