# Generated by Django 3.2.9 on 2021-11-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_inscricao_vagadeemprego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='vagaDeEmprego',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='empregador',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.empregador'),
        ),
    ]
